export class UserResponse {
  id: string;
  username: string;
  password: string;
  name: string;
  phone: string;
  email: string;
  status: string;
  activated: boolean;
  rememberToken: string;
  balance: number;
  luong: number;
  tongnap: number;
  online: boolean;
  role: string;
  groupId: string;
  lastLoginAt: Date;
  receivedFirstGift: boolean;
  lastAttendanceAt: Date;
  ipAddress: string;
  levelReward: number;
  note: string;
  banUntil: Date;
  createdAt: Date;
  updatedAt: Date;
  kh: string;
  tempCode: string;
  efffan: number;
  effvip: number;
  efftop: number;
  effytb: number;
  effdg: number;
  effygt: number;
  effydc: number;
  effydh: number;
  amountUnpaid: number;
  mcs: number;
  vip: number;
  vnd: number;
  mocvip: number;
  nhanmocnap: number;
  rewardtop: number;

  constructor(data: any) {
    this.id = data.id || null;
    this.username = data.username || null;
    this.password = data.password || null;
    this.name = data.name || null;
    this.phone = data.phone || null;
    this.email = data.email || null;
    this.status = data.status || null;
    this.activated = data.activated || false;
    this.rememberToken = data.remember_token || null;
    this.balance = data.balance || 0;
    this.luong = data.luong || 0;
    this.tongnap = data.tongnap || 0;
    this.online = data.online || false;
    this.role = data.role || null;
    this.groupId = data.group_id || null;
    this.lastLoginAt = data.last_login_at || null;
    this.receivedFirstGift = data.received_first_gift || false;
    this.lastAttendanceAt = data.last_attendance_at || null;
    this.ipAddress = data.ip_address || null;
    this.levelReward = data.level_reward || 0;
    this.note = data.note || null;
    this.banUntil = data.ban_until || null;
    this.createdAt = data.created_at || new Date();
    this.updatedAt = data.updated_at || new Date();
    this.kh = data.kh || null;
    this.tempCode = data.tempCode || null;
    this.efffan = data.efffan || 0;
    this.effvip = data.effvip || 0;
    this.efftop = data.efftop || 0;
    this.effytb = data.effytb || 0;
    this.effdg = data.effdg || 0;
    this.effygt = data.effygt || 0;
    this.effydc = data.effydc || 0;
    this.effydh = data.effydh || 0;
    this.amountUnpaid = data.amount_unpaid || 0;
    this.mcs = data.mcs || 0;
    this.vip = data.vip || 0;
    this.vnd = data.vnd || 0;
    this.mocvip = data.mocvip || 0;
    this.nhanmocnap = data.nhanmocnap || 0;
    this.rewardtop = data.rewardtop || 0;
  }
}
